[workspace]
authors = ["Modular, Inc. <hello@modular.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly"]
name = "new_model"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
modular = "*"
